import { Page, Text, View, Document, StyleSheet, pdf, Image } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';

// Define PDF Styles
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#f5f5f5' },
  header: { fontSize: 24, marginBottom: 10, textAlign: 'center', color: '#2563eb', fontWeight: 'bold' },
  subHeader: { fontSize: 12, marginBottom: 20, textAlign: 'center', color: '#666' },
  section: { marginBottom: 15, padding: 15, backgroundColor: 'white', borderRadius: 5 },
  sectionTitle: { fontSize: 16, marginBottom: 10, color: '#1e40af', borderBottom: '1px solid #e5e7eb', paddingBottom: 5 },
  row: { flexDirection: 'row', marginBottom: 5 },
  label: { width: 100, fontSize: 10, color: '#666', fontWeight: 'bold' },
  value: { flex: 1, fontSize: 10, color: '#000' },
  card: { marginBottom: 10, padding: 10, backgroundColor: '#f8fafc', borderRadius: 3 },
  cardTitle: { fontSize: 12, fontWeight: 'bold', color: '#0f172a' },
  cardText: { fontSize: 10, color: '#475569', marginTop: 2 },
  footer: { position: 'absolute', bottom: 30, left: 0, right: 0, textAlign: 'center', fontSize: 8, color: '#999' }
});

// PDF Document Structure
const MyDocument = ({ plan }: { plan: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* HEADER */}
      <Text style={styles.header}>AI Fitness Plan</Text>
      <Text style={styles.subHeader}>Personalized Roadmap for {plan.user_name || "You"}</Text>

      {/* MOTIVATION */}
      <View style={styles.section}>
        <Text style={{ fontSize: 12, fontStyle: 'italic', textAlign: 'center', color: '#4b5563' }}>
          "{plan.motivation}"
        </Text>
      </View>

      {/* WORKOUT SECTION */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>🏋️ Today's Workout</Text>
        {plan.workout?.map((item: any, index: number) => (
          <View key={index} style={styles.card}>
            <Text style={styles.cardTitle}>{index + 1}. {item.exercise}</Text>
            <Text style={styles.cardText}>{item.sets} Sets  •  {item.reps} Reps</Text>
          </View>
        ))}
      </View>

      {/* DIET SECTION */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>🥗 Nutrition Plan</Text>
        {plan.diet?.map((item: any, index: number) => (
          <View key={index} style={styles.card}>
            <View style={styles.row}>
              <Text style={{...styles.cardTitle, color: '#2563eb', width: 80}}>{item.meal}</Text>
              <Text style={styles.cardTitle}>{item.food}</Text>
            </View>
            <Text style={{ fontSize: 9, color: '#64748b', marginLeft: 80 }}>{item.calories} Calories</Text>
          </View>
        ))}
      </View>

      {/* FOOTER */}
      <Text style={styles.footer}>Generated by AI Fitness Coach • Built with Next.js & Gemini</Text>
    </Page>
  </Document>
);

export const downloadPDF = async (plan: any) => {
  const blob = await pdf(<MyDocument plan={plan} />).toBlob();
  saveAs(blob, 'My_AI_Fitness_Plan.pdf');
};